//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace METROWIND.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("METROWIND.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string AppSend {
            get {
                return ResourceManager.GetString("AppSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology for a sustainable future.
        /// </summary>
        internal static string AppSub {
            get {
                return ResourceManager.GetString("AppSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How may we assist you?.
        /// </summary>
        internal static string AppSuport {
            get {
                return ResourceManager.GetString("AppSuport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a charging station.
        /// </summary>
        internal static string ChooseStation {
            get {
                return ResourceManager.GetString("ChooseStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact mode.
        /// </summary>
        internal static string CompactMode {
            get {
                return ResourceManager.GetString("CompactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology for a Sustainable Future.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet access.
        /// </summary>
        internal static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading news.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map types.
        /// </summary>
        internal static string MapTypes {
            get {
                return ResourceManager.GetString("MapTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satelite.
        /// </summary>
        internal static string Satelite {
            get {
                return ResourceManager.GetString("Satelite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine power.
        /// </summary>
        internal static string TubinePower {
            get {
                return ResourceManager.GetString("TubinePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string TurbineAddress {
            get {
                return ResourceManager.GetString("TurbineAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capaity factor.
        /// </summary>
        internal static string TurbineCapacity {
            get {
                return ResourceManager.GetString("TurbineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current carbon removal.
        /// </summary>
        internal static string TurbineCarbonRemoval {
            get {
                return ResourceManager.GetString("TurbineCarbonRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine details.
        /// </summary>
        internal static string TurbineDetails {
            get {
                return ResourceManager.GetString("TurbineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO₂ emissions offset.
        /// </summary>
        internal static string TurbineEmission {
            get {
                return ResourceManager.GetString("TurbineEmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine images.
        /// </summary>
        internal static string TurbineImages {
            get {
                return ResourceManager.GetString("TurbineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date.
        /// </summary>
        internal static string TurbineInstalationDateTime {
            get {
                return ResourceManager.GetString("TurbineInstalationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TurbineName {
            get {
                return ResourceManager.GetString("TurbineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbines.
        /// </summary>
        internal static string TurbinesCollection {
            get {
                return ResourceManager.GetString("TurbinesCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TurbineSearch {
            get {
                return ResourceManager.GetString("TurbineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new.
        /// </summary>
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
